version: "3.5"

services:
  palladion-script-api:
    container_name: palladion-script-api
    build:
      context: ./server
      dockerfile: ./Dockerfile
    ports:
      - 4000:4000
  vite-app:
    container_name: vite-app
    build:
      context: ./client
      dockerfile: ./Dockerfile
    ports:
      - 80:80
